### ISSUE TITLE
Lack of images 

### ISSUE THREAD

**Issue by zhangyiFly** [MidoriYakumo/learnopengl-qt3d#10]
the follow images not found in you project:
                ("skybox/skybox_posz.jpg"),
		("skybox/skybox_posy.jpg"),
		("skybox/skybox_posx.jpg"),
		("skybox/skybox_negz.jpg"),
		("skybox/skybox_negy.jpg"),
		("skybox/skybox_negx.jpg"),
		("Rock-Texture-Surface.jpg"),
		("planet_Quom1200.png"),
		("leg_showroom_spec.png"),
		("leg_showroom_ddn.png"),
		("leg_dif.png"),
		("helmet_showroom_spec.png"),
		("helmet_showroom_ddn.png"),
		("helmet_diff.png"),
		("hand_showroom_spec.png"),
		("hand_showroom_ddn.png"),
		("hand_dif.png"),
		("glass_dif.png"),
		("glass_ddn.png"),
		("body_showroom_spec.png"),
		("body_showroom_ddn.png"),
		("body_dif.png"),
		("arm_showroom_spec.png"),
		("arm_showroom_ddn.png"),
		("arm_dif.png"),

**Comment by MidoriYakumo** [comment]
Large assets auto downloading from learnopengl.com not available in windows, please read original articles or view [assets.pri](https://github.com/MidoriYakumo/learnopengl-qt3d/blob/master/assets.pri) for details
