### ISSUE TITLE
cc1plus.exe: out of memory allocating 1073745919 bytes

### ISSUE THREAD

**Issue by qyvlik** [MidoriYakumo/learnopengl-qt3d#2]
> `cc1plus.exe: out of memory allocating 1073745919 bytes`

因为 assets 文件夹下的资源文件太大，超过了 20 mb，所以编译时就报了内存分配错误。

编译环境为：

win7 Qt 5.7.0 MinGW

请原谅我还在用 32 位编译器。

**Comment by MidoriYakumo** [comment]
自行裁剪和压缩资源吧，素材什么的都是可以根据条件自己换的
你也可以从qrc中去除资源，并在Resource.qml相关处更改资源路由

**Comment by qyvlik** [comment]
@MidoriYakumo 我已经修改为从本地文件路径加载了。不过使用 32 位编译后允许的效果与你贴的效果差别挺大的。随后在说说那些例子的效果。

今天刮台风，不用上班~O(∩_∩)O~~

**Comment by MidoriYakumo** [comment]
gles兼容的例子都可以用qmlscene跑，没必要编译

**Comment by qyvlik** [comment]
@MidoriYakumo 确实是，不过使用 `qmlscene` 加载一些 Qt3D 例子，会出现关闭窗体，但是后台程序不退出的情况。

**Comment by MidoriYakumo** [comment]
@qyvlik 你用法不对要仔细看文档…我的例子都是可以用qmlscene创建窗口的
