### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by TanNgocDo** [MidoriYakumo/learnopengl-qt3d#6]
I saw some demo lacks of file and there are error message : 
For example, when I run "import model" :+1: 

> QML debugging is enabled. Only use this in a safe environment.
qml: In total 39 samples.
qml: [Resources] app:0:file:../
qml: [Resources] assets:0:file:../
qml: [Resources] isGL33Core: 0, isGLES30: 1, isGLES20: 0. 
qml: [Resources] app:1:qrc:/
qml: [Resources] isGL33Core: 0, isGLES30: 1, isGLES20: 0. 
qrc:/qml/model.qml: File not found

> 

Could you please check it ?

**Comment by MidoriYakumo** [comment]
I'm currently rewriting the code from scratch and with detailed comments, the progress can be found in ReadMe.md.
I feel sorry if you clicked samples not implemented in *branch master*.
Full samples can be found in *branch legacy*:
https://github.com/MidoriYakumo/learnopengl-qt3d/tree/legacy
model.qml:
https://github.com/MidoriYakumo/learnopengl-qt3d/blob/legacy/qml/model.qml

**Comment by MidoriYakumo** [comment]
Feel free to create issues~

**Comment by TanNgocDo** [comment]
Very nice, I will check it and consider to contribute. I also want to learn 3D in Qt3d
