### ISSUE TITLE
No examples working properly

### ISSUE THREAD

**Issue by BPie** [MidoriYakumo/learnopengl-qt3d#9]
Hi,
I can't get the program to work. The main program runs, but all examples show nothing but one-color canvas.

```
// while running I get some libpng warnings
libpng warning: iCCP: known incorrect sRGB profile

// after changing example
No render surface selector found in frame graph
No render surface selector found in frame graph
No camera found and automatic aspect ratio requested
No Input Settings found, keyboard and mouse events won't be handled
```

environment:
OpenGL 4.3 CoreProfile
Qt 5.7.1
Linux (fedora)

**Comment by MidoriYakumo** [comment]
@BPie Have you tested on Qt official Qt3D samples? I get similar situation on my NVidia card for Qt5.8.
I think there are some bugs in Qt.

**Comment by BPie** [comment]
Examples are working fine. I also have a Nvidia card with proprietary driver.

**Comment by MidoriYakumo** [comment]
@BPie How about running app.qml with qmlscene(GLES 2.0) under qml?
QML OpenGL context handling is buggy.

**Comment by mcallegari** [comment]
@MidoriYakumo just tested on Qt 5.9.1. All examples are blank with errors like:
```
No render surface selector found in frame graph
qml: VirtualKeys.targetHandler: null
```
Running app.qml with qmlscene shows just the first 2-3 examples and then the following appears 
`module "VirtualKey" is not installed`

I'm on Linux with an nVidia card too. `GL format: OpenUnspecified 4.3 CoreProfile` is detected.

By the way: GREAT initiative ! I believe this will help a lot of people to get around with Qt3D (me included)

**Comment by MidoriYakumo** [comment]
@mcallegari  #452f59e fixed issues introduced by Qt5.9
VirtualKey is a submodule required from https://github.com/MidoriYakumo/qml-virtualkey

**Comment by mcallegari** [comment]
@MidoriYakumo thanks. I confirm all works now, except for lighting examples, which are all almost black.

Nitpick: please add `wheelEnabled: true` to the main window [combo box](https://github.com/MidoriYakumo/learnopengl-qt3d/blob/master/qml/main.qml#L35)
It's awful to go through the examples with so many mouse clicks
(P.S. have you received my email ??)

**Comment by MidoriYakumo** [comment]
I have submitted missing light caster shader path in qrc, with **wheelEnabled** check it out!
I read the email, do you mean SpotLight caster direction?

**Comment by mcallegari** [comment]
@MidoriYakumo awesome ! Everything works well now, thanks !
